[package]
name = "webui"
version = "0.1.0"
authors = ["Josh Pc <hylands.joshua2002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
